2019-12-13 22:30:09,871 ERROR: Exception on /user/vinodh [GET] [in c:\users\mjvin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\mjvin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\mjvin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\mjvin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\mjvin\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\mjvin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\mjvin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\mjvin\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\microblog\app\routes.py", line 139, in user
    next_url=next_url, prev_url=prev_url)
  File "c:\users\mjvin\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\mjvin\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\mjvin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\mjvin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\mjvin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\mjvin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\mjvin\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\mjvin\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\mjvin\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\mjvin\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "D:\microblog\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "D:\microblog\app\templates\user.html", line 14, in block "app_content"
    <p>Last seen on: {{ moment(user.education).format('LLL') }}</p>
  File "c:\users\mjvin\appdata\local\programs\python\python37-32\lib\site-packages\flask_moment.py", line 130, in format
    return self._render("format('%s')" % (fmt or ''), refresh)
  File "c:\users\mjvin\appdata\local\programs\python\python37-32\lib\site-packages\flask_moment.py", line 123, in _render
    t = self._timestamp_as_iso_8601(self.timestamp)
  File "c:\users\mjvin\appdata\local\programs\python\python37-32\lib\site-packages\flask_moment.py", line 120, in _timestamp_as_iso_8601
    return timestamp.strftime('%Y-%m-%dT%H:%M:%S' + tz)
AttributeError: 'str' object has no attribute 'strftime'
2019-12-13 22:31:22,604 INFO: Microblog startup [in D:\microblog\app\__init__.py:49]
2019-12-13 22:33:12,778 INFO: Microblog startup [in D:\microblog\app\__init__.py:49]
2019-12-13 22:33:34,833 INFO: Microblog startup [in D:\microblog\app\__init__.py:49]
2019-12-13 22:39:04,760 INFO: Microblog startup [in D:\microblog\app\__init__.py:49]
2019-12-13 22:40:22,571 INFO: Microblog startup [in D:\microblog\app\__init__.py:49]
